### ISSUE TITLE
Different distributions for different orfs when input is genbank file

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#106]
In the current implementation by @kwade4, if a user wants to specify different omega distribution for different reading frames, they would need to use a `yaml` file to specify such values, for example:

```
orfs: 
  2849,3182:
    omega_classes: 3
    omega_shape: 1.5
    omega_dist: gamma
  
  0,837:
    omega_classes: 4
    omega_shape: 1.7
    omega_dist: gamma
  
  3173,3182:
    omega_classes: 5
    omega_shape: 1.9
    omega_dist: gamma
```

However, if user uses a `genbank` file as an input format to extract the orfs, the distribution would be the same for all orfs. @ArtPoon , would it be correct if we allow the user to specify that they want different distributions, and then we generate values for `omega_classes` and `omega_shape` randomly?
